# Generated by Django 3.1.6 on 2021-11-16 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipments_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('perf_id', models.SmallIntegerField()),
                ('eqp_code', models.CharField(max_length=200)),
                ('eqp_name', models.CharField(max_length=200)),
                ('eqp_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('perf_id', models.SmallIntegerField()),
                ('ymdms', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('perf_id', models.SmallIntegerField()),
                ('dashboard_id', models.IntegerField()),
                ('pn_name', models.CharField(max_length=50)),
                ('eqp_name', models.CharField(max_length=50)),
                ('ymdms', models.DateTimeField()),
                ('vol_tage', models.FloatField()),
                ('am_pere', models.FloatField()),
                ('ar_power', models.FloatField()),
                ('atv_power', models.FloatField()),
                ('rat_power', models.FloatField()),
                ('pw_factor', models.FloatField()),
                ('accrue_power', models.FloatField()),
                ('voltager_s', models.FloatField()),
                ('voltages_t', models.FloatField()),
                ('voltaget_r', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
