# Generated by Django 3.1.6 on 2021-11-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generation_atv_power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('perf_id', models.SmallIntegerField()),
                ('target', models.DateTimeField()),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('predict', models.FloatField()),
                ('error', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='predict_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_path', models.CharField(max_length=50)),
                ('train_datetime', models.DateTimeField()),
                ('train_interval', models.IntegerField()),
                ('predict_interval', models.IntegerField()),
                ('train_cycle', models.IntegerField()),
                ('predict_cycle', models.IntegerField()),
            ],
        ),
    ]
