# Generated by Django 3.1.6 on 2021-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=50)),
                ('process', models.CharField(max_length=50)),
                ('process_name', models.CharField(max_length=50)),
                ('thread', models.CharField(max_length=50)),
                ('thread_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pathname', models.CharField(max_length=200)),
                ('func_name', models.CharField(max_length=50)),
                ('lineno', models.CharField(max_length=50)),
                ('levelname', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('exc_info', models.TextField(blank=True)),
                ('exc_text', models.TextField(blank=True)),
                ('stack_info', models.TextField(blank=True)),
            ],
        ),
    ]
