# Generated by Django 3.1.6 on 2021-11-28 03:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_name', models.CharField(max_length=50)),
                ('image_version', models.CharField(max_length=50, null=True)),
                ('engine', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('container_id', models.CharField(max_length=100, null=True)),
                ('environment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('network', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('command', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('dockerfile', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=50)),
                ('container_name', models.CharField(max_length=50)),
                ('cycle', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None), size=None)),
                ('network', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=50)),
                ('process', models.IntegerField()),
                ('process_name', models.CharField(max_length=50)),
                ('thread', models.BigIntegerField()),
                ('thread_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pathname', models.CharField(max_length=200)),
                ('func_name', models.CharField(max_length=50)),
                ('lineno', models.IntegerField()),
                ('levelno', models.IntegerField()),
                ('levelname', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('exc_info', models.TextField(blank=True)),
                ('exc_text', models.TextField(blank=True)),
                ('stack_info', models.TextField(blank=True)),
            ],
        ),
    ]
